package Login;

import Main.Dashboard;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author agar
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        tuser.setBackground(new java.awt.Color(0,0,0,1));
        tpass.setBackground(new java.awt.Color(0,0,0,1));
        bexit.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tuser = new javax.swing.JTextField();
        tpass = new javax.swing.JPasswordField();
        bexit = new javax.swing.JButton();
        bLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(661, 431));
        setUndecorated(true);

        jPanel1.setMaximumSize(new java.awt.Dimension(661, 431));
        jPanel1.setMinimumSize(new java.awt.Dimension(661, 431));
        jPanel1.setPreferredSize(new java.awt.Dimension(661, 431));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 240));
        jLabel2.setText("Penerima Bantuan Sosial");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 340, 40));

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 240));
        jLabel3.setText("Aplikasi Rekomendasi Warga ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 400, 40));

        tuser.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        tuser.setForeground(java.awt.Color.gray);
        tuser.setText("Username");
        tuser.setToolTipText("");
        tuser.setBorder(null);
        tuser.setDisabledTextColor(java.awt.Color.gray);
        tuser.setName(""); // NOI18N
        tuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tuserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tuserFocusLost(evt);
            }
        });
        tuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuserActionPerformed(evt);
            }
        });
        tuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tuserKeyTyped(evt);
            }
        });
        jPanel1.add(tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 157, 200, 30));
        tuser.getAccessibleContext().setAccessibleName("");

        tpass.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        tpass.setForeground(java.awt.Color.gray);
        tpass.setText("******");
        tpass.setBorder(null);
        tpass.setDisabledTextColor(java.awt.Color.gray);
        tpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tpassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tpassFocusLost(evt);
            }
        });
        tpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpassActionPerformed(evt);
            }
        });
        tpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tpassKeyPressed(evt);
            }
        });
        jPanel1.add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 200, 40));

        bexit.setBackground(new java.awt.Color(0,0,0,1));
        bexit.setForeground(java.awt.Color.white);
        bexit.setBorder(null);
        bexit.setBorderPainted(false);
        bexit.setContentAreaFilled(false);
        bexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });
        jPanel1.add(bexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 0, 30, 40));

        bLogin.setBackground(new java.awt.Color(0,0,0,1));
        bLogin.setForeground(java.awt.Color.white);
        bLogin.setBorder(null);
        bLogin.setBorderPainted(false);
        bLogin.setContentAreaFilled(false);
        bLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });
        jPanel1.add(bLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 190, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bg.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpassActionPerformed

    private void tuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuserActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bexitActionPerformed

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
        String user = tuser.getText();
        String pass = tpass.getText();
        if (user.equals("admin") && pass.equals("admin")){
            JOptionPane.showMessageDialog(null,"Login Berhasil");
            new Dashboard().setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Login Gagal");
            tuser.setText("");
            tpass.setText("");
            tuser.requestFocus(true);
        }
    }//GEN-LAST:event_bLoginActionPerformed

    private void tuserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tuserKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tuserKeyTyped

    private void tuserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tuserFocusGained
        // TODO add your handling code here:
        if(tuser.getText().equals("Username")){
            tuser.setText("");
            tuser.setForeground(new Color(64,64,64));
        }
    }//GEN-LAST:event_tuserFocusGained

    private void tuserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tuserFocusLost
        // TODO add your handling code here:
        if(tuser.getText().equals("")){
            tuser.setText("Username");
            tuser.setForeground(new Color (64,64,64));
        }
    }//GEN-LAST:event_tuserFocusLost

    private void tpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tpassFocusGained
        // TODO add your handling code here:
        if(tpass.getText().equals("******")){
            tpass.setText("");
            tpass.setForeground(new Color (64,64,64));
        }
    }//GEN-LAST:event_tpassFocusGained

    private void tpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tpassFocusLost
        // TODO add your handling code here:
        if(tpass.getText().equals("")){
            tpass.setText("******");
            tpass.setForeground(new Color (64,64,64));
        }
    }//GEN-LAST:event_tpassFocusLost

    private void tpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpassKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String user = tuser.getText();
            String pass = tpass.getText();
            if (user.equals("admin") && pass.equals("admin")){
                JOptionPane.showMessageDialog(null,"Login Berhasil");
                new Dashboard().setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null,"Login Gagal");
                tuser.setText("");
                tpass.setText("");
                tuser.requestFocus(true);
        }
        }
    }//GEN-LAST:event_tpassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bexit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JTextField tuser;
    // End of variables declaration//GEN-END:variables
}
