/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

/**
 *
 * @author agar
 */
public class beranda extends javax.swing.JPanel {

    /**
     * Creates new form beranda
     */
    public beranda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        gambarcontent = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 240));
        setMaximumSize(new java.awt.Dimension(623, 449));
        setPreferredSize(new java.awt.Dimension(623, 449));
        setLayout(new java.awt.CardLayout());

        content.setBackground(new java.awt.Color(255, 255, 240));
        content.setMaximumSize(new java.awt.Dimension(623, 449));
        content.setMinimumSize(new java.awt.Dimension(623, 449));
        content.setPreferredSize(new java.awt.Dimension(623, 449));

        gambarcontent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/gambarCOntainer.png"))); // NOI18N

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gambarcontent, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gambarcontent, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(content, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JLabel gambarcontent;
    // End of variables declaration//GEN-END:variables
}
