/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Login.Login;
import MenuHitung.hasilAkhir;
import MenuHitung.normalisasi;
import MenuLaporan.LBobotNilai;
import MenuLaporan.LDataPenerima;
import MenuLaporan.LHasil;
import MenuLaporan.LKriteria;
import MenuLaporan.LNormalisasi;
import MenuUtama.dataBobotNilai;
import MenuUtama.dataCalonPenerima;
import MenuUtama.dataKriteria;
import java.awt.Event;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author agar
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        execute();
        
        //Membuat timer dengan delay 1000 ms (1 detik)
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
               showDayDateTime();
            }
        });
        //memulai timer
        timer.start();
    }

    public void showDayDateTime(){
        Calendar calendar = Calendar.getInstance();
        Date now = new Date();
        SimpleDateFormat dayFormat = new SimpleDateFormat("EEEE",new Locale("in","ID"));
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd MMMM yyyy HH:mm:ss", new Locale("in", "ID"));
        String dayTime = dayFormat.format(calendar.getTime());
        String dateTime = dateFormat.format(now);
        LTgl.setText(dayTime+", "+dateTime);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dNavbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LTgl = new javax.swing.JLabel();
        dSideBar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pMenu = new javax.swing.JPanel();
        dContainer = new javax.swing.JPanel();
        dUtama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        dNavbar.setBackground(new java.awt.Color(0, 95, 105));
        dNavbar.setMaximumSize(new java.awt.Dimension(773, 100));
        dNavbar.setMinimumSize(new java.awt.Dimension(773, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/NavLogo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 240));
        jLabel2.setText("Aplikasi Rekomendasi Warga Penerima Bantuan Sosial");

        LTgl.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        LTgl.setForeground(new java.awt.Color(255, 255, 240));
        LTgl.setText("Hari, Tanggal dan Waktu");

        javax.swing.GroupLayout dNavbarLayout = new javax.swing.GroupLayout(dNavbar);
        dNavbar.setLayout(dNavbarLayout);
        dNavbarLayout.setHorizontalGroup(
            dNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dNavbarLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(dNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dNavbarLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(187, 187, 187))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dNavbarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        dNavbarLayout.setVerticalGroup(
            dNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dNavbarLayout.createSequentialGroup()
                .addGroup(dNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dNavbarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                    .addGroup(dNavbarLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(LTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(dNavbar, java.awt.BorderLayout.PAGE_START);

        dSideBar.setBackground(new java.awt.Color(0, 95, 105));
        dSideBar.setMaximumSize(new java.awt.Dimension(245, 449));
        dSideBar.setMinimumSize(new java.awt.Dimension(245, 449));
        dSideBar.setPreferredSize(new java.awt.Dimension(245, 449));

        jScrollPane2.setBackground(new java.awt.Color(0, 95, 105));
        jScrollPane2.setBorder(null);

        pMenu.setBackground(new java.awt.Color(0, 95, 105));
        pMenu.setLayout(new javax.swing.BoxLayout(pMenu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(pMenu);

        javax.swing.GroupLayout dSideBarLayout = new javax.swing.GroupLayout(dSideBar);
        dSideBar.setLayout(dSideBarLayout);
        dSideBarLayout.setHorizontalGroup(
            dSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );
        dSideBarLayout.setVerticalGroup(
            dSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );

        getContentPane().add(dSideBar, java.awt.BorderLayout.LINE_START);

        dContainer.setBackground(new java.awt.Color(255, 255, 240));

        dUtama.setBackground(new java.awt.Color(255, 255, 240));
        dUtama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout dContainerLayout = new javax.swing.GroupLayout(dContainer);
        dContainer.setLayout(dContainerLayout);
        dContainerLayout.setHorizontalGroup(
            dContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
        );
        dContainerLayout.setVerticalGroup(
            dContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );

        getContentPane().add(dContainer, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1218, 582));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        dUtama.add(new beranda());
        dUtama.repaint();
        dUtama.revalidate();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LTgl;
    private javax.swing.JPanel dContainer;
    private javax.swing.JPanel dNavbar;
    private javax.swing.JPanel dSideBar;
    private javax.swing.JPanel dUtama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pMenu;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        //Masukan Gambar
        ImageIcon iconBeranda       = new ImageIcon(getClass().getResource("/gambar/Beranda.png"));
        ImageIcon iconUtama         = new ImageIcon(getClass().getResource("/gambar/menuUtama.png"));
        ImageIcon iconHitung        = new ImageIcon(getClass().getResource("/gambar/menuHitung.png"));
        ImageIcon iconReport        = new ImageIcon(getClass().getResource("/gambar/menuReport.png"));
        ImageIcon iconKeluar        = new ImageIcon(getClass().getResource("/gambar/Logout.png"));
        //subIconMenuUtama
        ImageIcon iconKriteria      = new ImageIcon(getClass().getResource("/gambar/Kriteria.png"));
        ImageIcon iconPenerima      = new ImageIcon(getClass().getResource("/gambar/dataPenerima.png"));
        ImageIcon iconBobot         = new ImageIcon(getClass().getResource("/gambar/BobotNilai.png"));
        //subIconMenuHitung
        //subIconMenuHitung
        ImageIcon iconNormalisasi   = new ImageIcon(getClass().getResource("/gambar/Normalisasi.png"));
        ImageIcon iconHasil         = new ImageIcon(getClass().getResource("/gambar/Hasil.png"));
        //subIconMenuReport
        ImageIcon iconSubLaporan    = new ImageIcon(getClass().getResource("/gambar/Laporan.png"));
        //subMenuUtama
        menuItem dataPenerima       = new menuItem (null, true, iconPenerima, "Data Calon Penerima", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                dUtama.removeAll();
                dUtama.add(new dataCalonPenerima());
                dUtama.repaint();
                dUtama.revalidate();
            }
        });
        menuItem kriteria           = new menuItem (null, true, iconKriteria, "Data Kriteria", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                dUtama.removeAll();
                dUtama.add(new dataKriteria());
                dUtama.repaint();
                dUtama.revalidate();
            }
        });
        menuItem bobotNilai       = new menuItem (null, true, iconBobot, "Data Bobot Nilai", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                dUtama.removeAll();
                dUtama.add(new dataBobotNilai());
                dUtama.repaint();
                dUtama.revalidate();
            }
        });
        //subMenuHitung
        menuItem normalisasi        = new menuItem (null, true, iconNormalisasi, "Normalisasi", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                dUtama.removeAll();
                dUtama.add(new normalisasi());
                dUtama.repaint();
                dUtama.revalidate();
            }
        });
        menuItem hasil              = new menuItem (null, true, iconHasil, "Hasil", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                dUtama.removeAll();
                dUtama.add(new hasilAkhir());
                dUtama.repaint();
                dUtama.revalidate();
            }
        });
        //subMenuReport
        menuItem lDataPenerima      = new menuItem (null, true, iconSubLaporan, "Laporan Data Calon Penerima", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                dUtama.removeAll();
                dUtama.add(new LDataPenerima());
                dUtama.repaint();
                dUtama.revalidate();
            }
        });
        menuItem lKriteria          = new menuItem (null, true, iconSubLaporan, "Laporan Data Kriteria", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                dUtama.removeAll();
                dUtama.add(new LKriteria());
                dUtama.repaint();
                dUtama.revalidate();
            }
        });
        menuItem lNormalisasi       = new menuItem (null, true, iconSubLaporan, "Laporan Normalisasi", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                dUtama.removeAll();
                dUtama.add(new LNormalisasi());
                dUtama.repaint();
                dUtama.revalidate();
            }
        });
        menuItem lBobotNilai        = new menuItem (null, true, iconSubLaporan, "Laporan Data Bobot Nilai", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                dUtama.removeAll();
                dUtama.add(new LBobotNilai());
                dUtama.repaint();
                dUtama.revalidate();
            }
        });
        menuItem lHasil             = new menuItem (null, true, iconSubLaporan, "Laporan Hasil", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                dUtama.removeAll();
                dUtama.add(new LHasil());
                dUtama.repaint();
                dUtama.revalidate();
            }
        });
        //Masukan Nama Menu
        menuItem beranda            = new menuItem (iconBeranda, false, null, "Beranda", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                dUtama.removeAll();
                dUtama.add(new beranda());
                dUtama.repaint();
                dUtama.revalidate();
            }
        });
        menuItem menuUtama          = new menuItem (iconUtama, false, null, "Utama", null,dataPenerima,kriteria,bobotNilai);
        menuItem menuHitung         = new menuItem (iconHitung, false, null, "Hitung", null,normalisasi,hasil);
        menuItem menuReport         = new menuItem (iconReport, false, null, "Laporan", null,lKriteria,lDataPenerima,lBobotNilai,lNormalisasi,lHasil);
        menuItem Logout             = new menuItem (iconKeluar, false, null, "Keluar", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int dialogBtn = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(null, "Anda yakin akan keluar?", null, dialogBtn);
                
                if (dialogResult == 0){
                dispose();
                new Login().setVisible(true);
                }else{}
            }
        });
        //Panggil Menu
        addMenu (beranda);
        addMenu (menuUtama,kriteria,dataPenerima,bobotNilai);
        addMenu (menuHitung,normalisasi,hasil);
        addMenu (menuReport,lKriteria,lDataPenerima,lBobotNilai,lNormalisasi,lHasil);
        addMenu (Logout);   
    }
    
    private void addMenu(menuItem... menu){
        for (int i = 0; i < menu.length; i++){
            pMenu.add(menu[i]);
            ArrayList <menuItem> subMenu = menu[i].getSubMenu();
            for (menuItem m : subMenu) {
                addMenu(m);
            }
        }
        pMenu.revalidate();
    }
}
