package Main;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Icon;

/**
 *
 * @author agar
 */

public class menuItem extends javax.swing.JPanel {

    /**
     * @return the submenu
     */
    public ArrayList<menuItem> getSubMenu() {
        return subMenu;
    }

    /**
     * Creates new form menuItem
     */
    private final ArrayList<menuItem> subMenu = new ArrayList<>();
    
    private ActionListener act;
    
    public menuItem(Icon icon, boolean sbm, Icon iconSub, String namaMenu, ActionListener act, menuItem... subMenu) {
        initComponents();
        
        licon.setIcon(icon);
        lnamaMenu.setText(namaMenu);
        liconSub.setIcon(iconSub);
        liconSub.setVisible(sbm);
        //cariPenjelasannya
        if(act != null){
            this.act = act;
        }
        this.setSize(new Dimension(Integer.MAX_VALUE, 45));
        this.setMaximumSize(new Dimension(Integer.MAX_VALUE, 45));
        this.setMinimumSize(new Dimension(Integer.MAX_VALUE, 45));
        
        for(int i = 0; i< subMenu.length; i++){
            this.subMenu.add(subMenu[i]);
            subMenu[i].setVisible(false);
        }
    }
    private boolean showing = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lnamaMenu = new javax.swing.JLabel();
        licon = new javax.swing.JLabel();
        liconSub = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 95, 105));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        lnamaMenu.setBackground(java.awt.Color.white);
        lnamaMenu.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lnamaMenu.setForeground(new java.awt.Color(255, 255, 240));
        lnamaMenu.setText("Menu Items");
        lnamaMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        licon.setBackground(new java.awt.Color(0, 95, 105));
        licon.setMaximumSize(new java.awt.Dimension(40, 40));
        licon.setMinimumSize(new java.awt.Dimension(40, 40));
        licon.setPreferredSize(new java.awt.Dimension(40, 40));

        liconSub.setBackground(new java.awt.Color(0, 95, 105));
        liconSub.setMaximumSize(new java.awt.Dimension(40, 40));
        liconSub.setMinimumSize(new java.awt.Dimension(40, 40));
        liconSub.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(licon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(liconSub, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lnamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(licon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(liconSub, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lnamaMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        setBackground(new Color(0,95,105));
        if(showing){
            hideMenu();
        }else{
            showMenu();
        }
        if (act != null){
            act.actionPerformed(null);
        }
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel licon;
    private javax.swing.JLabel liconSub;
    private javax.swing.JLabel lnamaMenu;
    // End of variables declaration//GEN-END:variables

    private void hideMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i =  subMenu.size() - 1; i >= 0; i--){
                    sleep();
                    subMenu.get(i).setVisible(false);
                    subMenu.get(i).hideMenu();
                }
                getParent().repaint();
                getParent().revalidate();
                showing = false;
            }
        }).start();
    }

    private void showMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < subMenu.size(); i++){
                    sleep();
                    subMenu.get(i).setVisible(true);
                }
                showing = true;
                getParent().repaint();
                getParent().revalidate();
            }
        }).start();
    }
    private void sleep() {
        try {
            Thread.sleep(20);
        } catch (Exception e) {
        }
    }
}
