/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenuUtama;

import java.sql.Connection;
import Koneksi.koneksi;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
/**
 *
 * @author agar
 */
public class dataKriteria extends javax.swing.JPanel {

    /**
     * Creates new form dataKriteria
     */
    private Connection connection = new koneksi().connect();
    private DefaultTableModel tabmode;
    
    public dataKriteria() {
        initComponents();
        kosong();
        aktif();
        datatable();
        setLayoutForm();
    }
    protected void setLayoutForm(){
        /*TableColumn a = tabelKriteria.getColumnModel().getColumn(0);
        TableColumn b = tabelKriteria.getColumnModel().getColumn(1);
        TableColumn c = tabelKriteria.getColumnModel().getColumn(2);
        DefaultTableCellRenderer cellren = new DefaultTableCellRenderer();
        cellren.setHorizontalAlignment(JLabel.CENTER);
        a.setCellRenderer(cellren);
        b.setCellRenderer(cellren);
        c.setCellRenderer(cellren);
        */
        JTableHeader header = tabelKriteria.getTableHeader();
        DefaultTableCellRenderer render = (DefaultTableCellRenderer)header.getDefaultRenderer();
        render.setHorizontalAlignment(JLabel.CENTER);
    }
    protected void aktif(){
        txtId.setEnabled(true);
        txtKriteria.setEnabled(true);
        cbSifatKriteria.setSelectedItem(null);
        txtBobotPref.setEnabled(true);
    }
    protected void kosong(){
        txtId.setText("");
        txtKriteria.setText("");
        cbSifatKriteria.setSelectedItem(null);
        txtBobotPref.setText("");
    }
    protected void datatable(){
        Object[] Baris={"ID","Nama Kriteria","Sifat Kriteria","Bobot Preferensi"};
        tabmode = new DefaultTableModel(null, Baris);
        try {
            String sql= "select * from Kriteria";
            java.sql.Statement stat = connection.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4)
                });
            }
            tabelKriteria.setModel(tabmode);
        }catch (Exception e){
        
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PUtama = new javax.swing.JPanel();
        dataKriteria = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bTambah = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelKriteria = new javax.swing.JTable();
        inputKriteria = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bSimpan = new javax.swing.JButton();
        bBatal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbSifatKriteria = new javax.swing.JComboBox<>();
        txtKriteria = new javax.swing.JTextField();
        bUbah1 = new javax.swing.JButton();
        bHapus1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtBobotPref = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        PUtama.setLayout(new java.awt.CardLayout());

        dataKriteria.setBackground(new java.awt.Color(255, 255, 240));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 128));
        jLabel2.setText("DATA KRITERIA");

        bTambah.setBackground(new java.awt.Color(255, 8, 0));
        bTambah.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        bTambah.setForeground(new java.awt.Color(255, 255, 240));
        bTambah.setText("TAMBAH");
        bTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        tabelKriteria.setBackground(new java.awt.Color(255, 255, 240));
        tabelKriteria.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        tabelKriteria.setForeground(new java.awt.Color(0, 0, 128));
        tabelKriteria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nama Kriteria", "Sifat Kriteria"
            }
        ));
        tabelKriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKriteriaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelKriteria);

        javax.swing.GroupLayout dataKriteriaLayout = new javax.swing.GroupLayout(dataKriteria);
        dataKriteria.setLayout(dataKriteriaLayout);
        dataKriteriaLayout.setHorizontalGroup(
            dataKriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataKriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataKriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                    .addGroup(dataKriteriaLayout.createSequentialGroup()
                        .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(dataKriteriaLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dataKriteriaLayout.setVerticalGroup(
            dataKriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataKriteriaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        PUtama.add(dataKriteria, "card2");

        inputKriteria.setBackground(new java.awt.Color(255, 255, 240));

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 128));
        jLabel3.setText("MASUKKAN KRITERIA");

        bSimpan.setBackground(new java.awt.Color(255, 8, 0));
        bSimpan.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        bSimpan.setForeground(new java.awt.Color(255, 255, 240));
        bSimpan.setText("SIMPAN");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bBatal.setBackground(new java.awt.Color(255, 8, 0));
        bBatal.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        bBatal.setForeground(new java.awt.Color(255, 255, 240));
        bBatal.setText("KEMBALI");
        bBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 128));
        jLabel4.setText("ID");

        txtId.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        txtId.setForeground(new java.awt.Color(0, 0, 128));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 128));
        jLabel5.setText("NAMA KRITERIA");

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 128));
        jLabel6.setText("SIFAT KRITERIA");

        cbSifatKriteria.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        cbSifatKriteria.setForeground(new java.awt.Color(0, 0, 128));
        cbSifatKriteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH --", "Benefit", "Cost" }));

        txtKriteria.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        txtKriteria.setForeground(new java.awt.Color(0, 0, 128));
        txtKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKriteriaActionPerformed(evt);
            }
        });

        bUbah1.setBackground(new java.awt.Color(255, 8, 0));
        bUbah1.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        bUbah1.setForeground(new java.awt.Color(255, 255, 240));
        bUbah1.setText("UBAH");
        bUbah1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bUbah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbah1ActionPerformed(evt);
            }
        });

        bHapus1.setBackground(new java.awt.Color(255, 8, 0));
        bHapus1.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        bHapus1.setForeground(new java.awt.Color(255, 255, 240));
        bHapus1.setText("HAPUS");
        bHapus1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapus1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 128));
        jLabel7.setText("BOBOT PREFERENSI");

        txtBobotPref.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        txtBobotPref.setForeground(new java.awt.Color(0, 0, 128));
        txtBobotPref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBobotPrefActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputKriteriaLayout = new javax.swing.GroupLayout(inputKriteria);
        inputKriteria.setLayout(inputKriteriaLayout);
        inputKriteriaLayout.setHorizontalGroup(
            inputKriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputKriteriaLayout.createSequentialGroup()
                .addGroup(inputKriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputKriteriaLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3))
                    .addGroup(inputKriteriaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(inputKriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputKriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputKriteriaLayout.createSequentialGroup()
                        .addGroup(inputKriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSifatKriteria, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtKriteria)
                            .addGroup(inputKriteriaLayout.createSequentialGroup()
                                .addGroup(inputKriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtId))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputKriteriaLayout.createSequentialGroup()
                        .addComponent(bUbah1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                        .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addComponent(txtBobotPref)))
        );
        inputKriteriaLayout.setVerticalGroup(
            inputKriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputKriteriaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbSifatKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBobotPref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(inputKriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUbah1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PUtama.add(inputKriteria, "card2");

        add(PUtama, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        // TODO add your handling code here:
        PUtama.removeAll();
        PUtama.repaint();
        PUtama.revalidate();
        kosong();
        txtId.requestFocus();
        datatable();
        PUtama.add(inputKriteria);
        PUtama.repaint();
        PUtama.revalidate();
        bSimpan.setVisible(true);
        bUbah1.setVisible(false);
        bHapus1.setVisible(false);
    }//GEN-LAST:event_bTambahActionPerformed

    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        // TODO add your handling code here:
        PUtama.removeAll();
        PUtama.repaint();
        PUtama.revalidate();
        
        PUtama.add(dataKriteria);
        PUtama.repaint();
        PUtama.revalidate();
    }//GEN-LAST:event_bBatalActionPerformed

    private void txtKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKriteriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKriteriaActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        String sql = "insert into Kriteria values (?,?,?,?)";
        try {
            PreparedStatement stat = connection.prepareStatement(sql);
            stat.setString(1, txtId.getText());
            stat.setString(2, txtKriteria.getText());
            stat.setString(3, cbSifatKriteria.getSelectedItem().toString());
            stat.setString(4, txtBobotPref.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            txtId.requestFocus();
            PUtama.removeAll();
            PUtama.repaint();
            PUtama.revalidate();

            PUtama.add(dataKriteria);
            PUtama.repaint();
            PUtama.revalidate();
            bSimpan.setVisible(true);
            datatable();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan");
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void tabelKriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKriteriaMouseClicked
        // TODO add your handling code here:
        
        
        int bar = tabelKriteria.getSelectedRow( );
        String  a = tabmode.getValueAt (bar, 0) .toString( );
        String  b = tabmode.getValueAt (bar, 1) .toString( );
        String  c = tabmode.getValueAt (bar, 2) .toString( );
        String  d = tabmode.getValueAt (bar, 3) .toString( );
        
        txtId.setText(a);
        txtKriteria.setText(b);
        cbSifatKriteria.setSelectedItem(c);
        txtBobotPref.setText(d);
      
        PUtama.removeAll();
        PUtama.repaint();
        PUtama.revalidate();
        
        PUtama.add(inputKriteria);
        PUtama.repaint();
        PUtama.revalidate();
        bSimpan.setVisible(false);
        bUbah1.setVisible(true);
        bHapus1.setVisible(true);
        datatable();
    }//GEN-LAST:event_tabelKriteriaMouseClicked

    private void bUbah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbah1ActionPerformed
        // TODO add your handling code here:
        try{
            String sql="UPDATE Kriteria set namaKriteria=?,sifatKriteria=?,bobotPreferensi=? where ID='"+txtId.getText()+"'";
            PreparedStatement stat=connection.prepareStatement(sql);
            stat.setString(1, txtKriteria.getText());
            stat.setString(2, cbSifatKriteria.getSelectedItem().toString());
            stat.setString(3, txtBobotPref.getText().toString());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Berhasil Diubah");
            kosong();
            txtId.requestFocus();
            PUtama.removeAll();
            PUtama.repaint();
            PUtama.revalidate();

            PUtama.add(dataKriteria);
            PUtama.repaint();
            PUtama.revalidate();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Data Gagal Diubah"+e);
        }
        datatable();
    }//GEN-LAST:event_bUbah1ActionPerformed

    private void bHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapus1ActionPerformed
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null,"Hapus","Konfirmasi Dialog",JOptionPane.YES_NO_CANCEL_OPTION);
            if (ok==0){
            String sql="delete from Kriteria where ID ='"+txtId.getText()+"'";
            try{
                PreparedStatement stat=connection.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus");
                kosong();
                txtId.requestFocus();
                PUtama.removeAll();
                PUtama.repaint();
                PUtama.revalidate();

                PUtama.add(dataKriteria);
                PUtama.repaint();
                PUtama.revalidate();
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null,"Data Gagal Dihapus"+e);
            }
            datatable();
        }
    }//GEN-LAST:event_bHapus1ActionPerformed

    private void txtBobotPrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBobotPrefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBobotPrefActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PUtama;
    private javax.swing.JButton bBatal;
    private javax.swing.JButton bHapus1;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah1;
    private javax.swing.JComboBox<String> cbSifatKriteria;
    private javax.swing.JPanel dataKriteria;
    private javax.swing.JPanel inputKriteria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelKriteria;
    private javax.swing.JTextField txtBobotPref;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtKriteria;
    // End of variables declaration//GEN-END:variables
}
