package MenuUtama;

import Koneksi.koneksi;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author agar
 */
public class dataCalonPenerima extends javax.swing.JPanel {
    private Connection connection = new koneksi().connect();
    private DefaultTableModel tabmode;
    double BPB,BTJ,BKR,BT;
    
    public dataCalonPenerima() {
        initComponents();
        kosong();
        aktif();
        datatable();
        setLayout();
    }

    private void setLayout(){
        JTableHeader header = tabelCalonPenerima.getTableHeader();
        DefaultTableCellRenderer render = (DefaultTableCellRenderer)header.getDefaultRenderer();
        render.setHorizontalAlignment(JLabel.CENTER);
    }
    private void aktif(){
       txtNik.setEnabled(true);
       txtNama.setEnabled(true);
       cbPendapatan.setSelectedItem(null);
       cbJT.setSelectedItem(null);
       cbKR.setSelectedItem(null);
       cbTransportasi.setSelectedItem(null);
    }
    private void kosong(){
       txtNik.setText("");
       txtNama.setText("");
       cbPendapatan.setSelectedItem(null);
       cbJT.setSelectedItem(null);
       cbKR.setSelectedItem(null);
       cbTransportasi.setSelectedItem(null);
    }
    private void datatable(){
       Object [] baris = {"NIK","Nama","Pendapatan Bulanan","Jumlah Tanggungan","Kepemilikan Rumah","Transportasi"};
       tabmode = new DefaultTableModel(null, baris);
        try {
            String sql               = "select * from dataPenerima ORDER BY NIK ASC";
            java.sql.Statement stat  = connection.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6),
                    
            });   
            }
            tabelCalonPenerima.setModel(tabmode);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PUtama = new javax.swing.JPanel();
        dataCalonPenerima = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bTambah = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelCalonPenerima = new javax.swing.JTable();
        inputDataCalonPenerima = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bSimpan = new javax.swing.JButton();
        bBatal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        bUbah1 = new javax.swing.JButton();
        bHapus1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbPendapatan = new javax.swing.JComboBox<>();
        txtNik = new javax.swing.JTextField();
        cbJT = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbKR = new javax.swing.JComboBox<>();
        cbTransportasi = new javax.swing.JComboBox<>();

        setLayout(new java.awt.CardLayout());

        PUtama.setLayout(new java.awt.CardLayout());

        dataCalonPenerima.setBackground(new java.awt.Color(255, 255, 240));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 128));
        jLabel2.setText("DATA CALON PENERIMA");

        bTambah.setBackground(new java.awt.Color(255, 8, 0));
        bTambah.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        bTambah.setForeground(new java.awt.Color(255, 255, 240));
        bTambah.setText("TAMBAH");
        bTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        tabelCalonPenerima.setBackground(new java.awt.Color(255, 255, 240));
        tabelCalonPenerima.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        tabelCalonPenerima.setForeground(new java.awt.Color(0, 0, 128));
        tabelCalonPenerima.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIK", "NAMA", "PENDAPATAN", "JUMLAH TANGGUNGAN", "KEPEMILIKAN RUMAH", "TRANSPORTASI"
            }
        ));
        tabelCalonPenerima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelCalonPenerimaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelCalonPenerima);

        javax.swing.GroupLayout dataCalonPenerimaLayout = new javax.swing.GroupLayout(dataCalonPenerima);
        dataCalonPenerima.setLayout(dataCalonPenerimaLayout);
        dataCalonPenerimaLayout.setHorizontalGroup(
            dataCalonPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataCalonPenerimaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataCalonPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                    .addGroup(dataCalonPenerimaLayout.createSequentialGroup()
                        .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(dataCalonPenerimaLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dataCalonPenerimaLayout.setVerticalGroup(
            dataCalonPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataCalonPenerimaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        PUtama.add(dataCalonPenerima, "card2");

        inputDataCalonPenerima.setBackground(new java.awt.Color(255, 255, 240));

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 128));
        jLabel3.setText("MASUKKAN DATA CALON PENERIMA");

        bSimpan.setBackground(new java.awt.Color(255, 8, 0));
        bSimpan.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        bSimpan.setForeground(new java.awt.Color(255, 255, 240));
        bSimpan.setText("SIMPAN");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bBatal.setBackground(new java.awt.Color(255, 8, 0));
        bBatal.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        bBatal.setForeground(new java.awt.Color(255, 255, 240));
        bBatal.setText("KEMBALI");
        bBatal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 128));
        jLabel4.setText("NIK");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 128));
        jLabel5.setText("NAMA ");

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 128));
        jLabel6.setText("PENDAPATAN BULANAN");

        txtNama.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        txtNama.setForeground(new java.awt.Color(0, 0, 128));
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        bUbah1.setBackground(new java.awt.Color(255, 8, 0));
        bUbah1.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        bUbah1.setForeground(new java.awt.Color(255, 255, 240));
        bUbah1.setText("UBAH");
        bUbah1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bUbah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbah1ActionPerformed(evt);
            }
        });

        bHapus1.setBackground(new java.awt.Color(255, 8, 0));
        bHapus1.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        bHapus1.setForeground(new java.awt.Color(255, 255, 240));
        bHapus1.setText("HAPUS");
        bHapus1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapus1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 128));
        jLabel7.setText("JUMLAH TANGGUNGAN");

        cbPendapatan.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        cbPendapatan.setForeground(new java.awt.Color(0, 0, 128));
        cbPendapatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH --", "Rp <= 1.000.000/bulan", "Rp <= 1.500.000/bulan", "Rp <= 2.000.000/bulan", "Rp <= 2.500.000/bulan", "Rp >2.500.000/bulan" }));
        cbPendapatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPendapatanActionPerformed(evt);
            }
        });

        txtNik.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        txtNik.setForeground(new java.awt.Color(0, 0, 128));
        txtNik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNikActionPerformed(evt);
            }
        });

        cbJT.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        cbJT.setForeground(new java.awt.Color(0, 0, 128));
        cbJT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH --", ">8 orang", "6-7 orang", "4-5 orang", "2-3 orang", "1 orang" }));
        cbJT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJTActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 128));
        jLabel8.setText("KEPEMILIKAN RUMAH");

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 128));
        jLabel9.setText("TRANSPORTASI");

        cbKR.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        cbKR.setForeground(new java.awt.Color(0, 0, 128));
        cbKR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH --", "Pribadi, Keluarga, Sewa<500rb", "Sewa <= 750rb", "Sewa > 750rb" }));
        cbKR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKRActionPerformed(evt);
            }
        });

        cbTransportasi.setFont(new java.awt.Font("DejaVu Sans", 1, 16)); // NOI18N
        cbTransportasi.setForeground(new java.awt.Color(0, 0, 128));
        cbTransportasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH --", "Jalan Kaki / Sepeda", "Transportasi Umum", "1 Kendaraan Bermotor", "2 Kendaraan Bermotor", ">2 Kendaraan Bermotor" }));
        cbTransportasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTransportasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputDataCalonPenerimaLayout = new javax.swing.GroupLayout(inputDataCalonPenerima);
        inputDataCalonPenerima.setLayout(inputDataCalonPenerimaLayout);
        inputDataCalonPenerimaLayout.setHorizontalGroup(
            inputDataCalonPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputDataCalonPenerimaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputDataCalonPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputDataCalonPenerimaLayout.createSequentialGroup()
                        .addGroup(inputDataCalonPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama)
                            .addGroup(inputDataCalonPenerimaLayout.createSequentialGroup()
                                .addGroup(inputDataCalonPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputDataCalonPenerimaLayout.createSequentialGroup()
                        .addComponent(bUbah1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, Short.MAX_VALUE)
                        .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addComponent(txtNik)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputDataCalonPenerimaLayout.createSequentialGroup()
                        .addGroup(inputDataCalonPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inputDataCalonPenerimaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(inputDataCalonPenerimaLayout.createSequentialGroup()
                                .addGroup(inputDataCalonPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(inputDataCalonPenerimaLayout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel8)
                                    .addComponent(cbPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(inputDataCalonPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addComponent(cbJT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbTransportasi, 0, 234, Short.MAX_VALUE))))
                        .addGap(39, 39, 39))
                    .addGroup(inputDataCalonPenerimaLayout.createSequentialGroup()
                        .addComponent(cbKR, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        inputDataCalonPenerimaLayout.setVerticalGroup(
            inputDataCalonPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputDataCalonPenerimaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputDataCalonPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputDataCalonPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbJT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputDataCalonPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputDataCalonPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTransportasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(inputDataCalonPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUbah1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        PUtama.add(inputDataCalonPenerima, "card2");

        add(PUtama, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        // TODO add your handling code here:
        PUtama.removeAll();
        PUtama.repaint();
        PUtama.revalidate();
        kosong();
        txtNik.requestFocus();
        datatable();
        PUtama.add(inputDataCalonPenerima);
        PUtama.repaint();
        PUtama.revalidate();
        bSimpan.setVisible(true);
        bUbah1.setVisible(false);
        bHapus1.setVisible(false);
    }//GEN-LAST:event_bTambahActionPerformed

    private void tabelCalonPenerimaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelCalonPenerimaMouseClicked
        // TODO add your handling code here:

        int bar = tabelCalonPenerima.getSelectedRow( );
        String  a = tabmode.getValueAt (bar, 0) .toString( );
        String  b = tabmode.getValueAt (bar, 1) .toString( );
        String  c = tabmode.getValueAt (bar, 2) .toString( );
        String  d = tabmode.getValueAt (bar, 3) .toString( );
        String  e = tabmode.getValueAt (bar, 4) .toString( );
        String  f = tabmode.getValueAt (bar, 5) .toString( );

        txtNik.setText(a);
        txtNama.setText(b);
        cbPendapatan.setSelectedItem(c);
        cbJT.setSelectedItem(d);
        cbKR.setSelectedItem(e);
        cbTransportasi.setSelectedItem(f);

        PUtama.removeAll();
        PUtama.repaint();
        PUtama.revalidate();

        PUtama.add(inputDataCalonPenerima);
        PUtama.repaint();
        PUtama.revalidate();
        bSimpan.setVisible(false);
        bUbah1.setVisible(true);
        bHapus1.setVisible(true);
        datatable();
    }//GEN-LAST:event_tabelCalonPenerimaMouseClicked
    private void cbPendapatan(){
        String pendapatan = cbPendapatan.getSelectedItem().toString();
                switch (pendapatan) {
                    case "Rp <= 1.000.000/bulan":
                        BPB = 5.00;
                        break;
                    case "Rp <= 1.500.000/bulan":
                        BPB = 4.00;
                        break;
                    case "Rp <= 2.000.000/bulan":
                        BPB = 3.00;
                        break;
                    case "Rp <= 2.500.000/bulan":
                        BPB = 2.00;
                        break;
                    case "Rp > 2.500.000/bulan":
                        BPB = 1.00;
                        break;
                }
    }
     private void cbjumlahTanggungan(){
        String JT = cbJT.getSelectedItem().toString();
                switch (JT) {
                    case ">8 orang":
                        BTJ = 5.00;
                        break;
                    case "6-7 orang":
                        BTJ = 4.00;
                        break;
                    case "4-5 orang":
                        BTJ = 3.00;
                        break;
                    case "2-3 orang":
                        BTJ = 2.00;
                        break;
                    case "1 orang":
                        BTJ = 1.00;
                        break;
                }
    }
    private void cbKepemilikanRumah(){
        String KR = cbKR.getSelectedItem().toString();
                switch (KR) {
                    case "Pribadi, Keluarga, Sewa<500rb":
                        BKR = 3.00;
                        break;
                    case "Sewa <= 750rb":
                        BKR = 2.00;
                        break;
                    case "Sewa > 750rb":
                        BKR = 1.00;
                        break;
                    }
    }
     private void cbTransportasi(){
        String Transportasi = cbTransportasi.getSelectedItem().toString();
                switch (Transportasi) {
                    case "Jalan Kaki / Sepeda":
                        BT = 5.00;
                        break;
                    case "Transportasi Umum":
                        BT = 4.00;
                        break;
                    case "1 Kendaraan Bermotor":
                        BT = 3.00;
                        break;
                    case "2 Kendaraan Bermotor":
                        BT = 2.00;
                        break;
                    case ">2 Kendaraan Bermotor":
                        BT = 1.00;
                        break;
                    }
    } 
    
    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        cbPendapatan();
        cbjumlahTanggungan();
        cbKepemilikanRumah();
        cbTransportasi();
        String sql = "insert into dataPenerima values (?,?,?,?,?,?,?,?,?,?)";
        try {
            PreparedStatement stat = connection.prepareStatement(sql);
            stat.setString(1, txtNik.getText());
            stat.setString(2, txtNama.getText());
            stat.setString(3, cbPendapatan.getSelectedItem().toString());
            stat.setString(4, cbJT.getSelectedItem().toString());
            stat.setString(5, cbKR.getSelectedItem().toString());
            stat.setString(6, cbTransportasi.getSelectedItem().toString());
            stat.setDouble(7, BPB);
            stat.setDouble(8, BTJ);
            stat.setDouble(9, BKR);
            stat.setDouble(10, BT);

            // Menjalankan update
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");

            // Reset form dan UI
            kosong();
            txtNik.requestFocus();
            PUtama.removeAll();
            PUtama.repaint();
            PUtama.revalidate();

            PUtama.add(dataCalonPenerima);
            PUtama.repaint();
            PUtama.revalidate();
            bSimpan.setVisible(true);
            datatable();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan: " +e);
        }

    }//GEN-LAST:event_bSimpanActionPerformed

    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        // TODO add your handling code here:
        PUtama.removeAll();
        PUtama.repaint();
        PUtama.revalidate();

        PUtama.add(dataCalonPenerima);
        PUtama.repaint();
        PUtama.revalidate();
    }//GEN-LAST:event_bBatalActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void bUbah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbah1ActionPerformed
        // TODO add your handling code here:
        cbPendapatan();
        cbjumlahTanggungan();
        cbKepemilikanRumah();
        cbTransportasi();
        try{
            String sql="UPDATE dataPenerima set NW=?,PB=?,JT=?,KR=?,TR=?,BPB=?,BTJ=?,BKR=?,BT=? where NIK='"+txtNik.getText()+"'";
            PreparedStatement stat=connection.prepareStatement(sql);
            stat.setString(1, txtNama.getText());
            stat.setString(2, cbPendapatan.getSelectedItem().toString());
            stat.setString(3, cbJT.getSelectedItem().toString());
            stat.setString(4, cbKR.getSelectedItem().toString());
            stat.setString(5, cbTransportasi.getSelectedItem().toString());
            stat.setDouble(6, BPB);
            stat.setDouble(7, BTJ);
            stat.setDouble(8, BKR);
            stat.setDouble(9, BT);

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Berhasil Diubah");
            kosong();
            txtNik.requestFocus();
            PUtama.removeAll();
            PUtama.repaint();
            PUtama.revalidate();

            PUtama.add(dataCalonPenerima);
            PUtama.repaint();
            PUtama.revalidate();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Data Gagal Diubah"+e);
        }
        datatable();
    }//GEN-LAST:event_bUbah1ActionPerformed

    private void bHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapus1ActionPerformed
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null,"Hapus","Konfirmasi Dialog",JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql="delete from dataPenerima where NIK ='"+txtNik.getText()+"'";
            try{
                PreparedStatement stat=connection.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus");
                kosong();
                txtNik.requestFocus();
                PUtama.removeAll();
                PUtama.repaint();
                PUtama.revalidate();

                PUtama.add(dataCalonPenerima);
                PUtama.repaint();
                PUtama.revalidate();
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null,"Data Gagal Dihapus"+e);
            }
            datatable();
        }
    }//GEN-LAST:event_bHapus1ActionPerformed

    private void txtNikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNikActionPerformed

    private void cbPendapatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPendapatanActionPerformed
        // TODO add your handling code here:
//        String sql = "insert into dataPenerima (bobotPendapatan) values (?) ";
//        try{
//        PreparedStatement stat = connection.prepareStatement(sql);
//        if (cbPendapatan.getSelectedItem() == "Rp <= 1.000.000/bulan"){
//            double bobot = 5.00;
//            stat.setDouble(1, bobot);
//            stat.executeUpdate();
//        }else if (cbPendapatan.getSelectedItem() == "Rp <= 1.500.000/bulan"){
//            double bobot = 4.00;
//            stat.setDouble(1, bobot);
//            stat.executeUpdate();
//        }else if (cbPendapatan.getSelectedItem() == "Rp <= 2.000.000/bulan"){
//            double bobot = 3.00;
//            stat.setDouble(1, bobot);
//            stat.executeUpdate();
//        }else if (cbPendapatan.getSelectedItem() == "Rp <= 2.500.000/bulan"){
//            double bobot = 2.00;
//            stat.setDouble(1, bobot);
//            stat.executeUpdate();
//        }else if (cbPendapatan.getSelectedItem() == "Rp <= 3.000.000/bulan"){
//            double bobot = 1.00;
//            stat.setDouble(1, bobot);
//            stat.executeUpdate();
//        }else if (cbPendapatan.getSelectedItem() == "Rp > 3.000.000/bulan"){
//            double bobot = 0.00;
//            stat.setDouble(1, bobot);
//            stat.executeUpdate();
//        }
//        }catch (Exception e) {
//            System.out.println(""+e);
//        }
    }//GEN-LAST:event_cbPendapatanActionPerformed

    private void cbJTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJTActionPerformed

    private void cbKRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKRActionPerformed

    private void cbTransportasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTransportasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTransportasiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PUtama;
    private javax.swing.JButton bBatal;
    private javax.swing.JButton bHapus1;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah1;
    private javax.swing.JComboBox<String> cbJT;
    private javax.swing.JComboBox<String> cbKR;
    private javax.swing.JComboBox<String> cbPendapatan;
    private javax.swing.JComboBox<String> cbTransportasi;
    private javax.swing.JPanel dataCalonPenerima;
    private javax.swing.JPanel inputDataCalonPenerima;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelCalonPenerima;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNik;
    // End of variables declaration//GEN-END:variables
}
